//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogging.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogsEntities : DbContext
    {
        public BlogsEntities()
            : base("name=BlogsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<bloger> blogers { get; set; }
        public virtual DbSet<moderator> moderators { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
