//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogging.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.blogers = new HashSet<bloger>();
            this.moderators = new HashSet<moderator>();
        }
        [Display(Name = "User Id")]

        public int userid { get; set; }
        [Display(Name = "First Name")]

        public string first_name { get; set; }
        [Display(Name = "Last Name")]

        public string last_name { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Email is requierd")]
        [RegularExpression("^[a-z0-9_\\+-]+(\\.[a-z0-9_\\+-]+)*@[a-z0-9-]+(\\.[a-z0-9]+)*\\.([a-z]{2,4})$", ErrorMessage = "Invalid email format.")]
        public string email { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Password is requierd")]
        [DataType(DataType.Password)]

        public string password { get; set; }
        
        [Display(Name = "Type")]
        public string user_type { get; set; }
        public IEnumerable<SelectListItem> Types { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bloger> blogers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<moderator> moderators { get; set; }
    }
    
}
